services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432

  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_SETTINGS_PRODUCTION=True
    depends_on:
      - db

  client: # New service for building static assets
    build: ./client
    volumes:
      - client_static_content:/app/build/client # Populates the named volume with build artifacts from /app/build/client

  # NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - client_static_content:/usr/share/nginx/html/client/build/:ro # Mounts static assets from the named volume
    depends_on:
      - server # For API calls
      - client # Ensures client assets are built and available
    restart: unless-stopped

volumes:
  postgres_data:
  client_static_content: # Named volume for client's static content
